# Generated by Django 4.2.20 on 2025-05-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_remove_group_admin_group_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='remember_me',
            field=models.BooleanField(default=False),
        ),
    ]
