# Generated by Django 4.2.20 on 2025-05-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_device_remember_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the user has verified their email address.'),
        ),
    ]
