# Generated by Django 4.2.20 on 2025-05-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_customuser_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='due_date',
        ),
        migrations.AddField(
            model_name='group',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
