# Generated by Django 4.2.20 on 2025-06-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_remove_todo_category_remove_todo_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
