# Generated by Django 4.2.20 on 2025-06-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
